# Gene name annotation using partitions generated by AMAS.

path = "/home/"

# Load SpydrPick outliers
outliers <- read.csv(paste(path, "outliers.txt", sep = ""), header = FALSE, sep = ' ')
colnames(outliers) <- c("pos1","pos2","distance","type","mi","mi_wo_gaps", "gap_effect", "extreme_outlier")

# Load AMAS partitions.txt file
partitions <- read.csv(paste(path, "partitions.txt", sep = ""), header = FALSE, sep = '=')
colnames(partitions) <- c("gene","range")

# Transform partitions df to search
library(dplyr)
library(tidyr)

df_genes <- partitions %>%
  separate(gene, c("p", "gene_suffix"), "_", remove = FALSE, extra = "merge")
df_genes$gene <- sub("_[0-9]+","",df_genes$gene_suffix)
df_genes <- df_genes %>%
  separate(range, c("start", "end"), "-")
df_genes$start <- as.numeric(as.character(df_genes$start))
df_genes$end <- as.numeric(as.character(df_genes$end))
df_genes$gene <- trimws(df_genes$gene, which = c("right"))

# Annotate genenames of positions of outliers
library(dplyr)

df_annotations <- outliers[,c(1,2,3,4,5,6,7,8)]
namevector <- c("gene_suffix1", "gene1", "gene_suffix2", "gene2")
df_annotations[ , namevector] <- NA

# Get unique position from all edges
df_unique_pos1 <- unique(df_annotations[c("pos1")])
colnames(df_unique_pos1)[colnames(df_unique_pos1) == "pos1"] <- "pos"
df_unique_pos2 <- unique(df_annotations[c("pos2")])
colnames(df_unique_pos2)[colnames(df_unique_pos2) == "pos2"] <- "pos"
df_unique_pos <- union(df_unique_pos1, df_unique_pos2)

for(i in 1:nrow(df_unique_pos)) {
    pos = df_unique_pos$pos[i]
    gene_suffix = df_genes$gene_suffix[df_genes$start <= pos & df_genes$end >= pos]
    gene = df_genes$gene[df_genes$start <= pos & df_genes$end >= pos]
    df_unique_pos$gene_suffix[i] = gene_suffix
    df_unique_pos$gene[i] = gene
}

for(i in 1:nrow(df_unique_pos)) {
  pos = df_unique_pos$pos[i]
  gene_suffix = df_unique_pos$gene_suffix[i]
  gene = df_unique_pos$gene[i]
  if(pos %in% df_annotations$pos1){
    df_annotations[df_annotations$pos1 == pos, ]$gene1 <- gene
    df_annotations[df_annotations$pos1 == pos, ]$gene_suffix1 <- gene_suffix
  }
  if(pos %in% df_annotations$pos2){
    df_annotations[df_annotations$pos2 == pos, ]$gene2 <- gene
    df_annotations[df_annotations$pos2 == pos, ]$gene_suffix2 <- gene_suffix
  }
}

## Save annotations into file
output <- df_annotations[, c("pos1", "gene1", "gene_suffix1", "pos2", "gene2", "gene_suffix2", "distance", "type", "mi", "extreme_outlier")]
write.csv(output, paste(path, "genenames.csv", sep = ""), row.names=FALSE, quote=FALSE)
